services:
  notebook:
    image: jupyter/all-spark-notebook:spark-3.5.0
    container_name: notebook
    ports:
      - "8888:8888"
    volumes:
      - ./datasets:/home/jovyan/work
    restart: unless-stopped
